#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

runApplication blockMesh
runApplication simpleFoam

if notTest $@
then
    # Create validation plots

    # Test if gnuplot exists on the system
    command -v gnuplot >/dev/null 2>&1 || {
        echo "gnuplot not found - skipping graph creation" 1>&2
        exit 1
    }

    # Copy results to the validation directory
    timeDir=$(foamListTimes -latestTime)
    sampleDir=postProcessing/sample/$timeDir
    benchDir=constant/benchmark/

    [ -d $sampleDir -a -d $benchDir ] || {
        echo "results/benchmark directory not found - skipping graph creation" 1>&2
        exit 1
    }

    # Test if awk exists on the system
    command -v awk >/dev/null 2>&1 || {
        echo "awk not found - skipping graph creation" 1>&2
        exit 1
    }

    Uref=$(awk '{print $2}' $sampleDir/Uref_U.xy)


    #########
    # Skin friction coefficient profile
    #########
    benchF=${benchDir}x_cf.dat
    Cx=($(foamDictionary -entry boundaryField.lowerWall.value -value $timeDir/Cx | \
        sed -n '/(/,/)/p' | sed -e 's/[()]//g;/^\s*$/d' | cut -d' ' -f1))
    tauX=($(foamDictionary -entry boundaryField.lowerWall.value -value $timeDir/wallShearStress | \
        sed -n '/(/,/)/p' | sed -e 's/[()]//g;/^\s*$/d' | cut -d' ' -f1))

    graphName="backwardStep2D_Cf.png"
    echo "Creating skin friction coefficient graph to $graphName"

    gnuplot <<EOF
        set terminal pngcairo font "helvetica,20" size 1000, 1000
        set output "$graphName"
        set xlabel "x/H"
        set ylabel "C_f" rotate by 0
        set xrange [-5:30]
        set yrange [-0.002:0.004]
        set lmargin 10
        set rmargin 1.5
        set tmargin 0.1
        set bmargin 3.2
        set grid
        set key bottom right

        Uref="${Uref}"
        hRef=0.0127
        benchF="${benchF}"
        Cx="${Cx[*]}"
        tauX="${tauX[*]}"

        plot sample [i=1:words(Cx)] '+' u (word(Cx, int(i))/hRef):(-word(tauX, int(i))/(0.5*Uref*Uref)) t "simpleFoam" w lines lc "blue", \
             benchF u (\$1):(\$2) t "Experiment" w points pt 7 lc "red" lw 2
EOF


    #########
    # Surface pressure coefficient profile
    #########
    benchF=${benchDir}x_cp.dat
    Cp=($(foamDictionary -entry boundaryField.lowerWall.value -value $timeDir/cp | \
        sed -n '/(/,/)/p' | sed -e 's/[()]//g;/^\s*$/d' | cut -d' ' -f1))

    graphName="backwardStep2D_Cp.png"
    echo "Creating surface pressure coefficient profile graph to $graphName"

    gnuplot <<EOF
        set terminal pngcairo font "helvetica,20" size 1000, 1000
        set output "$graphName"
        set xlabel "x/H"
        set ylabel "C_p" rotate by 0
        set xrange [-5:30]
        set yrange [-0.30:0.10]
        set lmargin 10
        set rmargin 1.5
        set tmargin 0.1
        set bmargin 3.2
        set grid
        set key bottom right

        hRef=0.0127
        benchF="${benchF}"
        Cx="${Cx[*]}"
        Cp="${Cp[*]}"

        plot sample [i=1:words(Cx)] '+' u (word(Cx, int(i))/hRef):(1.*word(Cp, int(i))) t "simpleFoam" w lines lc "blue", \
             benchF u (\$1):(\$2) t "Experiment" w points pt 7 lc "red" lw 2
EOF


    #########
    # Flow speed profiles
    #########
    graphName="backwardStep2D_U.png"
    echo "Creating flow speed profiles graph to $graphName"

    gnuplot <<EOF
        set terminal pngcairo font "helvetica,20" size 1000, 1000
        set output "$graphName"
        set xrange [-0.4:1.2]
        set yrange [0:3]
        set xlabel "U/U_0"
        set ylabel "y/h" rotate by 0
        set lmargin 10
        set rmargin 1.5
        set tmargin 0.1
        set bmargin 3.2
        set grid
        set key top left
        set format x "%.1f"
        set format y "%.1f"

        Uref=$Uref
        hRef=0.0127

        plot \
            "$sampleDir/x_by_h_01_U.xy" u (\$2/Uref):(\$1/hRef) w lines lw 2 lc rgb "red" t "x/h = 1", \
            "${benchDir}xH01_profiles.dat" u (\$3):(\$2) t "x/h = 1 (Exp.)" w points pt 7 lc "red" lw 2, \
            "$sampleDir/x_by_h_04_U.xy" u (\$2/Uref):(\$1/hRef) w lines lw 2 lc rgb "green" t "x/h = 4", \
            "${benchDir}xH04_profiles.dat" u (\$3):(\$2) t "x/h = 4 (Exp.)" w points pt 7 lc "green" lw 2, \
            "$sampleDir/x_by_h_06_U.xy" u (\$2/Uref):(\$1/hRef) w lines lw 2 lc rgb "blue" t "x/h = 6", \
            "${benchDir}xH06_profiles.dat" u (\$3):(\$2) t "x/h = 6 (Exp.)" w points pt 7 lc "blue" lw 2, \
            "$sampleDir/x_by_h_10_U.xy" u (\$2/Uref):(\$1/hRef) w lines lw 2 lc rgb "black" t "x/h = 10", \
            "${benchDir}xH10_profiles.dat" u (\$3):(\$2) t "x/h = 10 (Exp.)" w points pt 7 lc "black" lw 2
EOF


    #########
    # Shear stress profiles
    #########
    # Column order of R in benchmark
    R[5]="uu"
    R[6]="vv"
    R[7]="uv"

    # Column order of R in OpenFOAM
    Rof[5]=2
    Rof[6]=5
    Rof[7]=3

    for i in "${!R[@]}"
    do
        col=$i
        component=${R[${col}]}
        componentOF=${Rof[${col}]}

        graphName="backwardStep2D_"${component}".png"
        echo "Creating ${component} stress profiles graph to $graphName"
        gnuplot <<EOF
            set terminal pngcairo font "helvetica,20" size 1000, 1000
            set output "$graphName"
            set xrange [-15:15]
            set yrange [0:3]
            set xlabel "$component/(U_0*U_0)*1000"
            set ylabel "y/h" rotate by 0
            set lmargin 10
            set rmargin 1.5
            set tmargin 0.1
            set bmargin 3.2
            set grid
            set key top left
            set format x "%.1f"
            set format y "%.1f"

            Uref = 1000/($Uref*$Uref)
            hRef=0.0127
            col=$col
            comp=$componentOF

            plot \
                "$sampleDir/x_by_h_01_turbulenceProperties:devReff.xy" u (column(comp+0)*Uref):(\$1/hRef) w lines lw 2 lc rgb "red" t "x/h = 1", \
                "${benchDir}xH01_profiles.dat" u (column(col+0)):(\$2) t "x/h = 1 (Exp.)" w points pt 7 lc "red" lw 2, \
                "$sampleDir/x_by_h_04_turbulenceProperties:devReff.xy" u (column(comp+0)*Uref):(\$1/hRef) w lines lw 2 lc rgb "green" t "x/h = 4", \
                "${benchDir}xH04_profiles.dat" u (column(col+0)):(\$2) t "x/h = 4 (Exp.)" w points pt 7 lc "green" lw 2, \
                "$sampleDir/x_by_h_06_turbulenceProperties:devReff.xy" u (column(comp+0)*Uref):(\$1/hRef) w lines lw 2 lc rgb "blue" t "x/h = 6", \
                "${benchDir}xH06_profiles.dat" u (column(col+0)):(\$2) t "x/h = 6 (Exp.)" w points pt 7 lc "blue" lw 2, \
                "$sampleDir/x_by_h_10_turbulenceProperties:devReff.xy" u (column(comp+0)*Uref):(\$1/hRef) w lines lw 2 lc rgb "black" t "x/h = 10", \
                "${benchDir}xH10_profiles.dat" u (column(col+0)):(\$2) t "x/h = 10 (Exp.)" w points pt 7 lc "black" lw 2
EOF
    done
fi

#------------------------------------------------------------------------------
